### ISSUE TITLE
infinite loop bug in autoTester 

### ISSUE THREAD

**Issue by WiIIiamTang** [TheBigSasha/COMP250_Assignment_1_W2020_Published_Debugger#1]
On line 387 of autoTester.java,

```java
while (customers[i].getBalance() > customers[i].getBasket().getTotalCost())`

```
may cause an unintentional infinite loop.

**Cause**: Inside the loop, a random hotel reservation is generated with a fixed seed. The number of nights is random, using ```nextInt(15)``` to generate a number between 0 - 15. When the number of nights is 0, the total cost of becomes 0. The customer's balance is then always larger than the total cost.

**Fix**: Set number of nights to not take the value 0, or do not fix the seed.

**Comment by TheBigSasha** [comment]
This has been patched out in the latest version by adding 1 to the output of the randomizer. Thank you for your feedback!
